import {
  GitBranch, Terminal, Cpu, Shield, Lock, Globe, Zap
} from "lucide-react";

export const THEMES = {
  dark: {
    isDark:       true,
    bg:           "#080c14",
    bgCard:       "#0f172a",
    bgSurface:    "#1e293b",
    bgElevated:   "#334155",
    bgHover:      "#1e293b",
    border:       "#1e293b",
    borderMid:    "#334155",
    borderStrong: "#475569",
    ink:          "#f8fafc",
    inkMid:       "#94a3b8",
    inkLow:       "#64748b",
    inkMuted:     "#475569",
    teal:         "#00f2fe",
    tealLight:    "#38bdf8",
    tealSoft:     "#0c2a3a",
    tealBord:     "#0369a1",
    tealMid:      "#0284c7",
    green:        "#10b981",
    greenSoft:    "#064e3b",
    greenBord:    "#047857",
    greenMid:     "#34d399",
    red:          "#ef4444",
    redSoft:      "#450a0a",
    redBord:      "#b91c1c",
    redMid:       "#f87171",
    amber:        "#f59e0b",
    amberSoft:    "#451a03",
    amberBord:    "#b45309",
    amberMid:     "#fbbf24",
    blue:         "#3b82f6",
    blueSoft:     "#172554",
    blueBord:     "#1d4ed8",
    blueMid:      "#60a5fa",
    violet:       "#a855f7",
    violetSoft:   "#3b0764",
    violetBord:   "#7e22ce",
    cyan:         "#06b6d4",
    cyanSoft:     "#083344",
    cyanBord:     "#0e7490",
    borderBright: "#334155",
    mono: "'JetBrains Mono','Fira Code','Courier New',monospace",
    sans: "'Plus Jakarta Sans',-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif",
  },
  light: {
    isDark:       false,
    bg:           "#f8fafc",
    bgCard:       "#ffffff",
    bgSurface:    "#f1f5f9",
    bgElevated:   "#e8edf3",
    bgHover:      "#f0f4f8",
    border:       "#e2e8f0",
    borderMid:    "#cbd5e1",
    borderStrong: "#94a3b8",
    ink:          "#0f172a",
    inkMid:       "#334155",
    inkLow:       "#64748b",
    inkMuted:     "#94a3b8",
    teal:         "#0d9488",
    tealLight:    "#14b8a6",
    tealSoft:     "#f0fdfa",
    tealBord:     "#99f6e4",
    tealMid:      "#5eead4",
    green:        "#10b981",
    greenSoft:    "#f0fdf4",
    greenBord:    "#bbf7d0",
    greenMid:     "#34d399",
    red:          "#ef4444",
    redSoft:      "#fff1f2",
    redBord:      "#fecdd3",
    redMid:       "#f87171",
    amber:        "#f59e0b",
    amberSoft:    "#fffbeb",
    amberBord:    "#fde68a",
    amberMid:     "#fbbf24",
    blue:         "#3b82f6",
    blueSoft:     "#eff6ff",
    blueBord:     "#bfdbfe",
    blueMid:      "#60a5fa",
    violet:       "#7c3aed",
    violetSoft:   "#f5f3ff",
    violetBord:   "#ddd6fe",
    cyan:         "#06b6d4",
    cyanSoft:     "#ecfeff",
    cyanBord:     "#a5f3fc",
    borderBright: "#cbd5e1",
    mono: "'JetBrains Mono','Fira Code','Courier New',monospace",
    sans: "'Plus Jakarta Sans',-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif",
  }
};

export const BACKEND = "https://secureflow-backend-1083585992526.us-central1.run.app";

export const PIPELINE_STAGES = [
  { key: "checkout",  label: "Checkout",     Icon: GitBranch },
  { key: "code_scan", label: "Code Scan",    Icon: Terminal  },
  { key: "docker",    label: "Docker Build", Icon: Cpu       },
  { key: "trivy",     label: "Trivy Scan",   Icon: Shield    },
  { key: "policy",    label: "Policy Gate",  Icon: Lock      },
  { key: "deploy",    label: "Deploy",       Icon: Globe     },
  { key: "zap",       label: "ZAP DAST",     Icon: Zap       },
];
